### ISSUE TITLE
Development plans

### ISSUE THREAD

**Issue by btk** [kaaninel/EmpatiJS#1]
Hey, are you looking forward to developing and adding more features to this project? Do you have a plan?

**Comment by kaaninel** [comment]
Yes, I'm using it for my projects and adding lots of function in my local. I will update this version soon. Didn't updated this one so far because I was developing a dom manipulation extension (two-way bindings etc) for it its not stable enough so i wont release that extension. If you want any other function just let me know.

**Comment by btk** [comment]
I have been looking for a similar project to contribute for a long time, are you looking for any help or partner for maintaining this project? If so, I'm down.

Seems like this project can take any path that you like, but the urgent things that I see is that console is throwing lots of native errors when pushing the code to its limits, an error pipeline (that would communicate errors, warning etc. to developer) interface via developer console seems like has the biggest priority.

As I saw there is no tests, as I was playing around supplying unwanted inputs for methods results unexpected outcomes. There it a lot to do and I would love to help if you like to explain your development plan and share the latest version of your code 👍 

Thank you.

**Comment by kaaninel** [comment]
I just looked to my code and it's just a mess right now. Actually I was developing a cms called Empati and this project is for client-side libraries of it. I wanna keep this part(main lib) as clean as possible and use an extension system(add extra functionalities with modules) so it can fit to every project. I wrote a basic extension for SPA applications (change page content via js and keep js globals etc) but its too messy i can't publish it. But i will publish a part of dom extensions code we can continue on that and fix this library. I really wanna develop this project but currently working on a project so i dint had much time.  It will take some time but with enough effort we can write a good library i believe.  If you want we  can talk about development plan in somewhere like facebook messenger, whatsapp or discord? 

Thanks for your interest on my project :)

**Comment by btk** [comment]
Discord looks good, just email me at iletisim@buraktokak.com when you are free for working on this project.

**Comment by kaaninel** [comment]
https://discord.gg/3UEns9v

We will continue discussing about this project in this channel. Anybody who wanna contribute can join to channel.

**Comment by kaaninel** [comment]
https://github.com/kaaninel/EmpatiJSDom

An example extension that i mentioned earlier.
